# Site Settings
baseurl: "/Grape-Theme"
url : "https://YolandaWang87.github.io"

# Blog Settings
theme_settings :
  title : My Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/PEI_beach.jpg
    username : Yolanda Wang
    description : This is my study blog and sandbox of web development.
    experience :
      - start : 2015-07-22
        experience : Geographic data processing
    skills : 
      - skill : Matlab
        value : 33  # Percent value
      - skill : Python 
        value : 5
      - skill : GIS 
        value : 5
      - skill : Web Development 
        value : 5
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: 
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true

port: 5050
